/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiE2eFingerprintRouteImport } from './routes/api.e2e-fingerprint'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedRemitosRouteImport } from './routes/_authenticated/remitos'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated/proveedores'
import { Route as AuthenticatedPagosProveedoresRouteImport } from './routes/_authenticated/pagos-proveedores'
import { Route as AuthenticatedPagosRouteImport } from './routes/_authenticated/pagos'
import { Route as AuthenticatedGastosRouteImport } from './routes/_authenticated/gastos'
import { Route as AuthenticatedFacturacionRouteImport } from './routes/_authenticated/facturacion'
import { Route as AuthenticatedCuentasCorrientesRouteImport } from './routes/_authenticated/cuentas-corrientes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCajaRouteImport } from './routes/_authenticated/caja'
import { Route as AuthenticatedArqueoRouteImport } from './routes/_authenticated/arqueo'
import { Route as AuthenticatedVentasIndexRouteImport } from './routes/_authenticated/ventas.index'
import { Route as AuthenticatedProductosIndexRouteImport } from './routes/_authenticated/productos.index'
import { Route as AuthenticatedPresupuestosIndexRouteImport } from './routes/_authenticated/presupuestos.index'
import { Route as AuthenticatedIngresosMercaderiaIndexRouteImport } from './routes/_authenticated/ingresos-mercaderia.index'
import { Route as AuthenticatedFacturacionIndexRouteImport } from './routes/_authenticated/facturacion.index'
import { Route as AuthenticatedComprasIndexRouteImport } from './routes/_authenticated/compras.index'
import { Route as AuthenticatedVentasNuevaRouteImport } from './routes/_authenticated/ventas.nueva'
import { Route as AuthenticatedProductosImportarRouteImport } from './routes/_authenticated/productos.importar'
import { Route as AuthenticatedPresupuestosNuevoRouteImport } from './routes/_authenticated/presupuestos.nuevo'
import { Route as AuthenticatedPresupuestosIdRouteImport } from './routes/_authenticated/presupuestos.$id'
import { Route as AuthenticatedIngresosMercaderiaNuevoRouteImport } from './routes/_authenticated/ingresos-mercaderia.nuevo'
import { Route as AuthenticatedFacturacionConfiguracionRouteImport } from './routes/_authenticated/facturacion.configuracion'
import { Route as AuthenticatedFacturacionColaRouteImport } from './routes/_authenticated/facturacion.cola'
import { Route as AuthenticatedComprasNuevaRouteImport } from './routes/_authenticated/compras.nueva'
import { Route as AuthenticatedProductosIdSeguimientoRouteImport } from './routes/_authenticated/productos.$id.seguimiento'
import { Route as AuthenticatedPresupuestosEditarIdRouteImport } from './routes/_authenticated/presupuestos.editar.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiE2eFingerprintRoute = ApiE2eFingerprintRouteImport.update({
  id: '/api/e2e-fingerprint',
  path: '/api/e2e-fingerprint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemitosRoute = AuthenticatedRemitosRouteImport.update({
  id: '/remitos',
  path: '/remitos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagosProveedoresRoute =
  AuthenticatedPagosProveedoresRouteImport.update({
    id: '/pagos-proveedores',
    path: '/pagos-proveedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagosRoute = AuthenticatedPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGastosRoute = AuthenticatedGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacturacionRoute =
  AuthenticatedFacturacionRouteImport.update({
    id: '/facturacion',
    path: '/facturacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCuentasCorrientesRoute =
  AuthenticatedCuentasCorrientesRouteImport.update({
    id: '/cuentas-corrientes',
    path: '/cuentas-corrientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCajaRoute = AuthenticatedCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArqueoRoute = AuthenticatedArqueoRouteImport.update({
  id: '/arqueo',
  path: '/arqueo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentasIndexRoute =
  AuthenticatedVentasIndexRouteImport.update({
    id: '/ventas/',
    path: '/ventas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductosIndexRoute =
  AuthenticatedProductosIndexRouteImport.update({
    id: '/productos/',
    path: '/productos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPresupuestosIndexRoute =
  AuthenticatedPresupuestosIndexRouteImport.update({
    id: '/presupuestos/',
    path: '/presupuestos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIngresosMercaderiaIndexRoute =
  AuthenticatedIngresosMercaderiaIndexRouteImport.update({
    id: '/ingresos-mercaderia/',
    path: '/ingresos-mercaderia/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacturacionIndexRoute =
  AuthenticatedFacturacionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFacturacionRoute,
  } as any)
const AuthenticatedComprasIndexRoute =
  AuthenticatedComprasIndexRouteImport.update({
    id: '/compras/',
    path: '/compras/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVentasNuevaRoute =
  AuthenticatedVentasNuevaRouteImport.update({
    id: '/ventas/nueva',
    path: '/ventas/nueva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductosImportarRoute =
  AuthenticatedProductosImportarRouteImport.update({
    id: '/productos/importar',
    path: '/productos/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPresupuestosNuevoRoute =
  AuthenticatedPresupuestosNuevoRouteImport.update({
    id: '/presupuestos/nuevo',
    path: '/presupuestos/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPresupuestosIdRoute =
  AuthenticatedPresupuestosIdRouteImport.update({
    id: '/presupuestos/$id',
    path: '/presupuestos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIngresosMercaderiaNuevoRoute =
  AuthenticatedIngresosMercaderiaNuevoRouteImport.update({
    id: '/ingresos-mercaderia/nuevo',
    path: '/ingresos-mercaderia/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacturacionConfiguracionRoute =
  AuthenticatedFacturacionConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedFacturacionRoute,
  } as any)
const AuthenticatedFacturacionColaRoute =
  AuthenticatedFacturacionColaRouteImport.update({
    id: '/cola',
    path: '/cola',
    getParentRoute: () => AuthenticatedFacturacionRoute,
  } as any)
const AuthenticatedComprasNuevaRoute =
  AuthenticatedComprasNuevaRouteImport.update({
    id: '/compras/nueva',
    path: '/compras/nueva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductosIdSeguimientoRoute =
  AuthenticatedProductosIdSeguimientoRouteImport.update({
    id: '/productos/$id/seguimiento',
    path: '/productos/$id/seguimiento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPresupuestosEditarIdRoute =
  AuthenticatedPresupuestosEditarIdRouteImport.update({
    id: '/presupuestos/editar/$id',
    path: '/presupuestos/editar/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/arqueo': typeof AuthenticatedArqueoRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/cuentas-corrientes': typeof AuthenticatedCuentasCorrientesRoute
  '/facturacion': typeof AuthenticatedFacturacionRouteWithChildren
  '/gastos': typeof AuthenticatedGastosRoute
  '/pagos': typeof AuthenticatedPagosRoute
  '/pagos-proveedores': typeof AuthenticatedPagosProveedoresRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/remitos': typeof AuthenticatedRemitosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/stock': typeof AuthenticatedStockRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/e2e-fingerprint': typeof ApiE2eFingerprintRoute
  '/compras/nueva': typeof AuthenticatedComprasNuevaRoute
  '/facturacion/cola': typeof AuthenticatedFacturacionColaRoute
  '/facturacion/configuracion': typeof AuthenticatedFacturacionConfiguracionRoute
  '/ingresos-mercaderia/nuevo': typeof AuthenticatedIngresosMercaderiaNuevoRoute
  '/presupuestos/$id': typeof AuthenticatedPresupuestosIdRoute
  '/presupuestos/nuevo': typeof AuthenticatedPresupuestosNuevoRoute
  '/productos/importar': typeof AuthenticatedProductosImportarRoute
  '/ventas/nueva': typeof AuthenticatedVentasNuevaRoute
  '/compras/': typeof AuthenticatedComprasIndexRoute
  '/facturacion/': typeof AuthenticatedFacturacionIndexRoute
  '/ingresos-mercaderia/': typeof AuthenticatedIngresosMercaderiaIndexRoute
  '/presupuestos/': typeof AuthenticatedPresupuestosIndexRoute
  '/productos/': typeof AuthenticatedProductosIndexRoute
  '/ventas/': typeof AuthenticatedVentasIndexRoute
  '/presupuestos/editar/$id': typeof AuthenticatedPresupuestosEditarIdRoute
  '/productos/$id/seguimiento': typeof AuthenticatedProductosIdSeguimientoRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/arqueo': typeof AuthenticatedArqueoRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/cuentas-corrientes': typeof AuthenticatedCuentasCorrientesRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/pagos': typeof AuthenticatedPagosRoute
  '/pagos-proveedores': typeof AuthenticatedPagosProveedoresRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/remitos': typeof AuthenticatedRemitosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/stock': typeof AuthenticatedStockRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/e2e-fingerprint': typeof ApiE2eFingerprintRoute
  '/': typeof AuthenticatedIndexRoute
  '/compras/nueva': typeof AuthenticatedComprasNuevaRoute
  '/facturacion/cola': typeof AuthenticatedFacturacionColaRoute
  '/facturacion/configuracion': typeof AuthenticatedFacturacionConfiguracionRoute
  '/ingresos-mercaderia/nuevo': typeof AuthenticatedIngresosMercaderiaNuevoRoute
  '/presupuestos/$id': typeof AuthenticatedPresupuestosIdRoute
  '/presupuestos/nuevo': typeof AuthenticatedPresupuestosNuevoRoute
  '/productos/importar': typeof AuthenticatedProductosImportarRoute
  '/ventas/nueva': typeof AuthenticatedVentasNuevaRoute
  '/compras': typeof AuthenticatedComprasIndexRoute
  '/facturacion': typeof AuthenticatedFacturacionIndexRoute
  '/ingresos-mercaderia': typeof AuthenticatedIngresosMercaderiaIndexRoute
  '/presupuestos': typeof AuthenticatedPresupuestosIndexRoute
  '/productos': typeof AuthenticatedProductosIndexRoute
  '/ventas': typeof AuthenticatedVentasIndexRoute
  '/presupuestos/editar/$id': typeof AuthenticatedPresupuestosEditarIdRoute
  '/productos/$id/seguimiento': typeof AuthenticatedProductosIdSeguimientoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/arqueo': typeof AuthenticatedArqueoRoute
  '/_authenticated/caja': typeof AuthenticatedCajaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/cuentas-corrientes': typeof AuthenticatedCuentasCorrientesRoute
  '/_authenticated/facturacion': typeof AuthenticatedFacturacionRouteWithChildren
  '/_authenticated/gastos': typeof AuthenticatedGastosRoute
  '/_authenticated/pagos': typeof AuthenticatedPagosRoute
  '/_authenticated/pagos-proveedores': typeof AuthenticatedPagosProveedoresRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/remitos': typeof AuthenticatedRemitosRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/e2e-fingerprint': typeof ApiE2eFingerprintRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/compras/nueva': typeof AuthenticatedComprasNuevaRoute
  '/_authenticated/facturacion/cola': typeof AuthenticatedFacturacionColaRoute
  '/_authenticated/facturacion/configuracion': typeof AuthenticatedFacturacionConfiguracionRoute
  '/_authenticated/ingresos-mercaderia/nuevo': typeof AuthenticatedIngresosMercaderiaNuevoRoute
  '/_authenticated/presupuestos/$id': typeof AuthenticatedPresupuestosIdRoute
  '/_authenticated/presupuestos/nuevo': typeof AuthenticatedPresupuestosNuevoRoute
  '/_authenticated/productos/importar': typeof AuthenticatedProductosImportarRoute
  '/_authenticated/ventas/nueva': typeof AuthenticatedVentasNuevaRoute
  '/_authenticated/compras/': typeof AuthenticatedComprasIndexRoute
  '/_authenticated/facturacion/': typeof AuthenticatedFacturacionIndexRoute
  '/_authenticated/ingresos-mercaderia/': typeof AuthenticatedIngresosMercaderiaIndexRoute
  '/_authenticated/presupuestos/': typeof AuthenticatedPresupuestosIndexRoute
  '/_authenticated/productos/': typeof AuthenticatedProductosIndexRoute
  '/_authenticated/ventas/': typeof AuthenticatedVentasIndexRoute
  '/_authenticated/presupuestos/editar/$id': typeof AuthenticatedPresupuestosEditarIdRoute
  '/_authenticated/productos/$id/seguimiento': typeof AuthenticatedProductosIdSeguimientoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/arqueo'
    | '/caja'
    | '/clientes'
    | '/cuentas-corrientes'
    | '/facturacion'
    | '/gastos'
    | '/pagos'
    | '/pagos-proveedores'
    | '/proveedores'
    | '/remitos'
    | '/reportes'
    | '/stock'
    | '/usuarios'
    | '/api/e2e-fingerprint'
    | '/compras/nueva'
    | '/facturacion/cola'
    | '/facturacion/configuracion'
    | '/ingresos-mercaderia/nuevo'
    | '/presupuestos/$id'
    | '/presupuestos/nuevo'
    | '/productos/importar'
    | '/ventas/nueva'
    | '/compras/'
    | '/facturacion/'
    | '/ingresos-mercaderia/'
    | '/presupuestos/'
    | '/productos/'
    | '/ventas/'
    | '/presupuestos/editar/$id'
    | '/productos/$id/seguimiento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/arqueo'
    | '/caja'
    | '/clientes'
    | '/cuentas-corrientes'
    | '/gastos'
    | '/pagos'
    | '/pagos-proveedores'
    | '/proveedores'
    | '/remitos'
    | '/reportes'
    | '/stock'
    | '/usuarios'
    | '/api/e2e-fingerprint'
    | '/'
    | '/compras/nueva'
    | '/facturacion/cola'
    | '/facturacion/configuracion'
    | '/ingresos-mercaderia/nuevo'
    | '/presupuestos/$id'
    | '/presupuestos/nuevo'
    | '/productos/importar'
    | '/ventas/nueva'
    | '/compras'
    | '/facturacion'
    | '/ingresos-mercaderia'
    | '/presupuestos'
    | '/productos'
    | '/ventas'
    | '/presupuestos/editar/$id'
    | '/productos/$id/seguimiento'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/arqueo'
    | '/_authenticated/caja'
    | '/_authenticated/clientes'
    | '/_authenticated/cuentas-corrientes'
    | '/_authenticated/facturacion'
    | '/_authenticated/gastos'
    | '/_authenticated/pagos'
    | '/_authenticated/pagos-proveedores'
    | '/_authenticated/proveedores'
    | '/_authenticated/remitos'
    | '/_authenticated/reportes'
    | '/_authenticated/stock'
    | '/_authenticated/usuarios'
    | '/api/e2e-fingerprint'
    | '/_authenticated/'
    | '/_authenticated/compras/nueva'
    | '/_authenticated/facturacion/cola'
    | '/_authenticated/facturacion/configuracion'
    | '/_authenticated/ingresos-mercaderia/nuevo'
    | '/_authenticated/presupuestos/$id'
    | '/_authenticated/presupuestos/nuevo'
    | '/_authenticated/productos/importar'
    | '/_authenticated/ventas/nueva'
    | '/_authenticated/compras/'
    | '/_authenticated/facturacion/'
    | '/_authenticated/ingresos-mercaderia/'
    | '/_authenticated/presupuestos/'
    | '/_authenticated/productos/'
    | '/_authenticated/ventas/'
    | '/_authenticated/presupuestos/editar/$id'
    | '/_authenticated/productos/$id/seguimiento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiE2eFingerprintRoute: typeof ApiE2eFingerprintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/e2e-fingerprint': {
      id: '/api/e2e-fingerprint'
      path: '/api/e2e-fingerprint'
      fullPath: '/api/e2e-fingerprint'
      preLoaderRoute: typeof ApiE2eFingerprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remitos': {
      id: '/_authenticated/remitos'
      path: '/remitos'
      fullPath: '/remitos'
      preLoaderRoute: typeof AuthenticatedRemitosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagos-proveedores': {
      id: '/_authenticated/pagos-proveedores'
      path: '/pagos-proveedores'
      fullPath: '/pagos-proveedores'
      preLoaderRoute: typeof AuthenticatedPagosProveedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagos': {
      id: '/_authenticated/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AuthenticatedPagosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gastos': {
      id: '/_authenticated/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof AuthenticatedGastosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturacion': {
      id: '/_authenticated/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof AuthenticatedFacturacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuentas-corrientes': {
      id: '/_authenticated/cuentas-corrientes'
      path: '/cuentas-corrientes'
      fullPath: '/cuentas-corrientes'
      preLoaderRoute: typeof AuthenticatedCuentasCorrientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caja': {
      id: '/_authenticated/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AuthenticatedCajaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arqueo': {
      id: '/_authenticated/arqueo'
      path: '/arqueo'
      fullPath: '/arqueo'
      preLoaderRoute: typeof AuthenticatedArqueoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas/': {
      id: '/_authenticated/ventas/'
      path: '/ventas'
      fullPath: '/ventas/'
      preLoaderRoute: typeof AuthenticatedVentasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productos/': {
      id: '/_authenticated/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof AuthenticatedProductosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presupuestos/': {
      id: '/_authenticated/presupuestos/'
      path: '/presupuestos'
      fullPath: '/presupuestos/'
      preLoaderRoute: typeof AuthenticatedPresupuestosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ingresos-mercaderia/': {
      id: '/_authenticated/ingresos-mercaderia/'
      path: '/ingresos-mercaderia'
      fullPath: '/ingresos-mercaderia/'
      preLoaderRoute: typeof AuthenticatedIngresosMercaderiaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturacion/': {
      id: '/_authenticated/facturacion/'
      path: '/'
      fullPath: '/facturacion/'
      preLoaderRoute: typeof AuthenticatedFacturacionIndexRouteImport
      parentRoute: typeof AuthenticatedFacturacionRoute
    }
    '/_authenticated/compras/': {
      id: '/_authenticated/compras/'
      path: '/compras'
      fullPath: '/compras/'
      preLoaderRoute: typeof AuthenticatedComprasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas/nueva': {
      id: '/_authenticated/ventas/nueva'
      path: '/ventas/nueva'
      fullPath: '/ventas/nueva'
      preLoaderRoute: typeof AuthenticatedVentasNuevaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productos/importar': {
      id: '/_authenticated/productos/importar'
      path: '/productos/importar'
      fullPath: '/productos/importar'
      preLoaderRoute: typeof AuthenticatedProductosImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presupuestos/nuevo': {
      id: '/_authenticated/presupuestos/nuevo'
      path: '/presupuestos/nuevo'
      fullPath: '/presupuestos/nuevo'
      preLoaderRoute: typeof AuthenticatedPresupuestosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presupuestos/$id': {
      id: '/_authenticated/presupuestos/$id'
      path: '/presupuestos/$id'
      fullPath: '/presupuestos/$id'
      preLoaderRoute: typeof AuthenticatedPresupuestosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ingresos-mercaderia/nuevo': {
      id: '/_authenticated/ingresos-mercaderia/nuevo'
      path: '/ingresos-mercaderia/nuevo'
      fullPath: '/ingresos-mercaderia/nuevo'
      preLoaderRoute: typeof AuthenticatedIngresosMercaderiaNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturacion/configuracion': {
      id: '/_authenticated/facturacion/configuracion'
      path: '/configuracion'
      fullPath: '/facturacion/configuracion'
      preLoaderRoute: typeof AuthenticatedFacturacionConfiguracionRouteImport
      parentRoute: typeof AuthenticatedFacturacionRoute
    }
    '/_authenticated/facturacion/cola': {
      id: '/_authenticated/facturacion/cola'
      path: '/cola'
      fullPath: '/facturacion/cola'
      preLoaderRoute: typeof AuthenticatedFacturacionColaRouteImport
      parentRoute: typeof AuthenticatedFacturacionRoute
    }
    '/_authenticated/compras/nueva': {
      id: '/_authenticated/compras/nueva'
      path: '/compras/nueva'
      fullPath: '/compras/nueva'
      preLoaderRoute: typeof AuthenticatedComprasNuevaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productos/$id/seguimiento': {
      id: '/_authenticated/productos/$id/seguimiento'
      path: '/productos/$id/seguimiento'
      fullPath: '/productos/$id/seguimiento'
      preLoaderRoute: typeof AuthenticatedProductosIdSeguimientoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/presupuestos/editar/$id': {
      id: '/_authenticated/presupuestos/editar/$id'
      path: '/presupuestos/editar/$id'
      fullPath: '/presupuestos/editar/$id'
      preLoaderRoute: typeof AuthenticatedPresupuestosEditarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedFacturacionRouteChildren {
  AuthenticatedFacturacionColaRoute: typeof AuthenticatedFacturacionColaRoute
  AuthenticatedFacturacionConfiguracionRoute: typeof AuthenticatedFacturacionConfiguracionRoute
  AuthenticatedFacturacionIndexRoute: typeof AuthenticatedFacturacionIndexRoute
}

const AuthenticatedFacturacionRouteChildren: AuthenticatedFacturacionRouteChildren =
  {
    AuthenticatedFacturacionColaRoute: AuthenticatedFacturacionColaRoute,
    AuthenticatedFacturacionConfiguracionRoute:
      AuthenticatedFacturacionConfiguracionRoute,
    AuthenticatedFacturacionIndexRoute: AuthenticatedFacturacionIndexRoute,
  }

const AuthenticatedFacturacionRouteWithChildren =
  AuthenticatedFacturacionRoute._addFileChildren(
    AuthenticatedFacturacionRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArqueoRoute: typeof AuthenticatedArqueoRoute
  AuthenticatedCajaRoute: typeof AuthenticatedCajaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCuentasCorrientesRoute: typeof AuthenticatedCuentasCorrientesRoute
  AuthenticatedFacturacionRoute: typeof AuthenticatedFacturacionRouteWithChildren
  AuthenticatedGastosRoute: typeof AuthenticatedGastosRoute
  AuthenticatedPagosRoute: typeof AuthenticatedPagosRoute
  AuthenticatedPagosProveedoresRoute: typeof AuthenticatedPagosProveedoresRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedRemitosRoute: typeof AuthenticatedRemitosRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedComprasNuevaRoute: typeof AuthenticatedComprasNuevaRoute
  AuthenticatedIngresosMercaderiaNuevoRoute: typeof AuthenticatedIngresosMercaderiaNuevoRoute
  AuthenticatedPresupuestosIdRoute: typeof AuthenticatedPresupuestosIdRoute
  AuthenticatedPresupuestosNuevoRoute: typeof AuthenticatedPresupuestosNuevoRoute
  AuthenticatedProductosImportarRoute: typeof AuthenticatedProductosImportarRoute
  AuthenticatedVentasNuevaRoute: typeof AuthenticatedVentasNuevaRoute
  AuthenticatedComprasIndexRoute: typeof AuthenticatedComprasIndexRoute
  AuthenticatedIngresosMercaderiaIndexRoute: typeof AuthenticatedIngresosMercaderiaIndexRoute
  AuthenticatedPresupuestosIndexRoute: typeof AuthenticatedPresupuestosIndexRoute
  AuthenticatedProductosIndexRoute: typeof AuthenticatedProductosIndexRoute
  AuthenticatedVentasIndexRoute: typeof AuthenticatedVentasIndexRoute
  AuthenticatedPresupuestosEditarIdRoute: typeof AuthenticatedPresupuestosEditarIdRoute
  AuthenticatedProductosIdSeguimientoRoute: typeof AuthenticatedProductosIdSeguimientoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArqueoRoute: AuthenticatedArqueoRoute,
  AuthenticatedCajaRoute: AuthenticatedCajaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCuentasCorrientesRoute: AuthenticatedCuentasCorrientesRoute,
  AuthenticatedFacturacionRoute: AuthenticatedFacturacionRouteWithChildren,
  AuthenticatedGastosRoute: AuthenticatedGastosRoute,
  AuthenticatedPagosRoute: AuthenticatedPagosRoute,
  AuthenticatedPagosProveedoresRoute: AuthenticatedPagosProveedoresRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedRemitosRoute: AuthenticatedRemitosRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedComprasNuevaRoute: AuthenticatedComprasNuevaRoute,
  AuthenticatedIngresosMercaderiaNuevoRoute:
    AuthenticatedIngresosMercaderiaNuevoRoute,
  AuthenticatedPresupuestosIdRoute: AuthenticatedPresupuestosIdRoute,
  AuthenticatedPresupuestosNuevoRoute: AuthenticatedPresupuestosNuevoRoute,
  AuthenticatedProductosImportarRoute: AuthenticatedProductosImportarRoute,
  AuthenticatedVentasNuevaRoute: AuthenticatedVentasNuevaRoute,
  AuthenticatedComprasIndexRoute: AuthenticatedComprasIndexRoute,
  AuthenticatedIngresosMercaderiaIndexRoute:
    AuthenticatedIngresosMercaderiaIndexRoute,
  AuthenticatedPresupuestosIndexRoute: AuthenticatedPresupuestosIndexRoute,
  AuthenticatedProductosIndexRoute: AuthenticatedProductosIndexRoute,
  AuthenticatedVentasIndexRoute: AuthenticatedVentasIndexRoute,
  AuthenticatedPresupuestosEditarIdRoute:
    AuthenticatedPresupuestosEditarIdRoute,
  AuthenticatedProductosIdSeguimientoRoute:
    AuthenticatedProductosIdSeguimientoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiE2eFingerprintRoute: ApiE2eFingerprintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
