/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedRemitosRouteImport } from './routes/_authenticated/remitos'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCajaRouteImport } from './routes/_authenticated/caja'
import { Route as AuthenticatedVentasIndexRouteImport } from './routes/_authenticated/ventas.index'
import { Route as AuthenticatedProductosIndexRouteImport } from './routes/_authenticated/productos.index'
import { Route as AuthenticatedVentasNuevaRouteImport } from './routes/_authenticated/ventas.nueva'
import { Route as AuthenticatedProductosImportarRouteImport } from './routes/_authenticated/productos.importar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemitosRoute = AuthenticatedRemitosRouteImport.update({
  id: '/remitos',
  path: '/remitos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCajaRoute = AuthenticatedCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVentasIndexRoute =
  AuthenticatedVentasIndexRouteImport.update({
    id: '/ventas/',
    path: '/ventas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductosIndexRoute =
  AuthenticatedProductosIndexRouteImport.update({
    id: '/productos/',
    path: '/productos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVentasNuevaRoute =
  AuthenticatedVentasNuevaRouteImport.update({
    id: '/ventas/nueva',
    path: '/ventas/nueva',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductosImportarRoute =
  AuthenticatedProductosImportarRouteImport.update({
    id: '/productos/importar',
    path: '/productos/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/remitos': typeof AuthenticatedRemitosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/stock': typeof AuthenticatedStockRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/productos/importar': typeof AuthenticatedProductosImportarRoute
  '/ventas/nueva': typeof AuthenticatedVentasNuevaRoute
  '/productos/': typeof AuthenticatedProductosIndexRoute
  '/ventas/': typeof AuthenticatedVentasIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/remitos': typeof AuthenticatedRemitosRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/stock': typeof AuthenticatedStockRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/': typeof AuthenticatedIndexRoute
  '/productos/importar': typeof AuthenticatedProductosImportarRoute
  '/ventas/nueva': typeof AuthenticatedVentasNuevaRoute
  '/productos': typeof AuthenticatedProductosIndexRoute
  '/ventas': typeof AuthenticatedVentasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/caja': typeof AuthenticatedCajaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/remitos': typeof AuthenticatedRemitosRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/productos/importar': typeof AuthenticatedProductosImportarRoute
  '/_authenticated/ventas/nueva': typeof AuthenticatedVentasNuevaRoute
  '/_authenticated/productos/': typeof AuthenticatedProductosIndexRoute
  '/_authenticated/ventas/': typeof AuthenticatedVentasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/caja'
    | '/clientes'
    | '/remitos'
    | '/reportes'
    | '/stock'
    | '/usuarios'
    | '/productos/importar'
    | '/ventas/nueva'
    | '/productos/'
    | '/ventas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/caja'
    | '/clientes'
    | '/remitos'
    | '/reportes'
    | '/stock'
    | '/usuarios'
    | '/'
    | '/productos/importar'
    | '/ventas/nueva'
    | '/productos'
    | '/ventas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/caja'
    | '/_authenticated/clientes'
    | '/_authenticated/remitos'
    | '/_authenticated/reportes'
    | '/_authenticated/stock'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
    | '/_authenticated/productos/importar'
    | '/_authenticated/ventas/nueva'
    | '/_authenticated/productos/'
    | '/_authenticated/ventas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remitos': {
      id: '/_authenticated/remitos'
      path: '/remitos'
      fullPath: '/remitos'
      preLoaderRoute: typeof AuthenticatedRemitosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caja': {
      id: '/_authenticated/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AuthenticatedCajaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas/': {
      id: '/_authenticated/ventas/'
      path: '/ventas'
      fullPath: '/ventas/'
      preLoaderRoute: typeof AuthenticatedVentasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productos/': {
      id: '/_authenticated/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof AuthenticatedProductosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ventas/nueva': {
      id: '/_authenticated/ventas/nueva'
      path: '/ventas/nueva'
      fullPath: '/ventas/nueva'
      preLoaderRoute: typeof AuthenticatedVentasNuevaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productos/importar': {
      id: '/_authenticated/productos/importar'
      path: '/productos/importar'
      fullPath: '/productos/importar'
      preLoaderRoute: typeof AuthenticatedProductosImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCajaRoute: typeof AuthenticatedCajaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedRemitosRoute: typeof AuthenticatedRemitosRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProductosImportarRoute: typeof AuthenticatedProductosImportarRoute
  AuthenticatedVentasNuevaRoute: typeof AuthenticatedVentasNuevaRoute
  AuthenticatedProductosIndexRoute: typeof AuthenticatedProductosIndexRoute
  AuthenticatedVentasIndexRoute: typeof AuthenticatedVentasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCajaRoute: AuthenticatedCajaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedRemitosRoute: AuthenticatedRemitosRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProductosImportarRoute: AuthenticatedProductosImportarRoute,
  AuthenticatedVentasNuevaRoute: AuthenticatedVentasNuevaRoute,
  AuthenticatedProductosIndexRoute: AuthenticatedProductosIndexRoute,
  AuthenticatedVentasIndexRoute: AuthenticatedVentasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
